apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: p8j2kbedq-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: p8j2kbedq-go 
  name: p8j2kbedq-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: p8j2kbedq-go 
